site_name: DSP-Metadata-GUI

nav:
  - Overview: index.md
  - Usage:
    - Usage Overview: usage_overview.md
    - Project Organization: list_view.md
    - Entering Metadata: tab_view.md
    - Metadata Classes:
      - Project: project.md
  - API Reference:
      - "GUI documentation": reference/collectMetadata.md
      - "Data Handling": reference/dataHandling.md
      - "Data Structure": reference/metaDataSet.md
  - Pending Tasks: todo.md

theme:
  name: material
  logo: 'assets/images/dasch-icon-white.svg'
  favicon: 'assets/images/dasch-favicon.ico'
  pallette:
    primary: 'deep purple'
    accent: 'deep purple'
  # features:
  #   - navigation.tabs
  feature:
    tabs: false
extra_css:
  - 'assets/style/theme.css'

markdown_extensions:
  - markdown_include.include
  - pymdownx.tasklist
  - pymdownx.critic

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_root_full_path: false
            # heading_level: 2
            show_source: false
            group_by_category: false
            # show_if_no_docstring: true
      watch:
        - util/
        - docs/
        - ./

