site_name: DSP-Metadata-GUI

nav:
  - Home:
    - Readme: index.md
    - Open Questions: todos_questions.md
    - Before you start: overview.md

  - List View:
    - List: list_view.md
  - Tabbed View:
    - Tabs Overview: tabs_overview.md
    - Base Data: basedata.md
    - Project: project.md
    - Data: data.md
    - Person: person.md
    - Organization: organization.md
    - Grant: grant.md
  - Code documentation:
      - "GUI documentation": collectMetadata.md
      - "Data Handling": dataHandling.md

theme:
  name: material
  logo: 'assets/images/dasch-icon-white.svg'
  favicon: 'assets/images/dasch-favicon.ico'
  pallette:
    primary: 'deep purple'
    accent: 'deep purple'
  features:
    - navigation.tabs
  extra_css:
    - 'assets/style/theme.css'

plugins:
  - mkdocstrings:
      watch:
        - util/
        - docs/
        - ./

