site_name: DSP-Metadata-GUI

nav:
  - Overview: index.md
  - Usage:
    - Usage Overview: usage_overview.md
    - Before you start: prep.md
  - Project Organization:
    - List: list_view.md
  - Tabbed View:
    - Tabs Overview: tabs_overview.md
    - Base Data: basedata.md
    - Project: project.md
    - Data: data.md
    - Person: person.md
    - Organization: organization.md
    - Grant: grant.md
  - API Reference:
      - "GUI documentation": reference/collectMetadata.md
      - "Data Handling": reference/dataHandling.md
      - "Data Structure": reference/metaDataSet.md
  - Pending Tasks: todo.md

theme:
  name: material
  logo: 'assets/images/dasch-icon-white.svg'
  favicon: 'assets/images/dasch-favicon.ico'
  pallette:
    primary: 'deep purple'
    accent: 'deep purple'
  # features:
  #   - navigation.tabs
  feature:
    tabs: false
extra_css:
  - 'assets/style/theme.css'

markdown_extensions:
  - markdown_include.include
  - pymdownx.tasklist

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_root_full_path: false
            # heading_level: 2
            show_source: false
            group_by_category: false
            # show_if_no_docstring: true
      watch:
        - util/
        - docs/
        - ./

