name: Release

on:
  release:
    types: [released]

# set environment variables
env:
  TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_USERNAME: ${{ secrets.PYPI_USER }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PW }}

jobs:
  # release to PyPI
  release-pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # check out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # install python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      # install pythonn dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
        # pip install -r requirements.txt  # will this break? avoid installing wPython!
      # release new version to PyPI
      - name: generate distribution package
        run: |
          make upgrade-dist-tools
          make dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PW }}

  release-docs:
    name: Release Docs
    runs-on: ubuntu-latest
    steps:
      # check out repo
      - uses: actions/checkout@v2
      # install python
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REQUIREMENTS: docs/requirements.txt

