name: Release

on:
  release:
    types: [released]

# set environment variables
env:
  TOKEN: ${{ secrets.GH_TOKEN }}
  POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
  POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_DASCHBOT_TOKEN }}

jobs:
  no-op:
    name: No-op
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "No-op"
        
  # release to PyPI
  release-pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # check out repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      # install python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      # install pythonn dependencies
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: build wheel
        run: |
          make upgrade-dist-tools
          make dist
      - name: publish new version to PyPI
        run: poetry publish

  release-docs:
    name: Release Docs
    runs-on: ubuntu-latest
    steps:
      # check out repo
      - uses: actions/checkout@v2
      # install python
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REQUIREMENTS: docs/requirements.txt

