name: Test

on:
  push:
  pull_request:
    types: [opened]

jobs:
  test-integration:
    name: Tests (ensures setup is working)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          # install python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      # install pythonn dependencies
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install


